Repository WildCodeSchool/lyon-js-sept21-p2-g2-front, pull requests merged in 2021-11, with the labels that each got.

#16 css issues fixed
  src/components/Team.jsx
Labels: Ready for prod

#19 Footer
  src/components/Footer.css
  src/components/Footer.jsx
Labels: Ready for prod

#14 Weather
  package-lock.json
  package.json
  src/components/Weather.jsx
  src/components/routes/Destination.jsx
  src/components/weather.css
  yarn.lock
Labels: Ready for prod

#21 destination bloc connected to the api
  public/index.html
  src/App.jsx
  src/assets/fav-icon.png
  src/components/DestinationBloc.jsx
  src/components/destinationBloc.css
Labels: Ready for prod

#20 Add and Link the 'Create Post' button with complete CSS
  src/components/CreatePostBtn.jsx
  src/components/createPostBtn.css
  src/components/routes/Dashboard.jsx
  src/components/routes/Destination.jsx
Labels: Ready for prod

#24 Destination bloc
  src/components/DestinationBloc.jsx
Labels: Ready for prod

#23 most valued destinations list created
  src/assets/Mont-Heavy.otf
  src/components/DestinationBloc.jsx
  src/components/MvdList.jsx
  src/components/routes/Home.jsx
  src/index.css
Labels: Ready for prod

#25 Weather
  .env.sample
  package-lock.json
  package.json
  src/components/Weather.jsx
  src/components/weather.css
  yarn.lock
Labels: Ready for prod

#22 Filter
  MyselectTag.js
  package-lock.json
  package.json
  src/assets/filter.png
  src/components/MySelectTag.css
  src/components/MySelectTag.jsx
  src/components/createPostBtn.css
  src/components/routes/Destination.jsx
  src/components/routes/Filter.css
  src/components/routes/Filter.jsx
  yarn.lock
Labels: Fixed - ready for prod

#26 css issues teween destinationBloc and the footer are fixed and I star…
  .eslintrc.json
  package-lock.json
  src/assets/Zag Regular.otf
  src/components/Converter.jsx
  src/components/DestinationBloc.jsx
  src/components/Footer.css
  src/components/MvdList.css
  src/components/MvdList.jsx
  src/components/Weather.jsx
  src/components/destinationBloc.css
  src/components/weather.css
  src/index.css
Labels: Ready for validation

#18 Search bar
  package-lock.json
  src/components/AbstractBlogPost.jsx
  src/components/DestinationBloc.jsx
  src/components/FullUserPost.jsx
  src/components/Header.jsx
  src/components/MvdList.css
  src/components/MvdList.jsx
  src/components/NewPostForm.jsx
  src/components/TagList.jsx
  src/components/Team.jsx
  src/components/routes/Home.css
  src/components/routes/Home.jsx
  src/css/AbstractBlogPost.css
  src/css/FullUserPost.css
  src/css/Header.css
  src/css/Home.css
  src/css/NewPostForm.css
  src/css/TagList.css
  src/css/Team.css
  src/css/destinationBloc.css
  src/css/index.css
  src/index.js
Labels: Ready for prod, Fixed - ready for prod

#28 Css modifications
  src/components/AbstractBlogPost.jsx
  src/components/Converter.jsx
  src/components/CreatePostBtn.jsx
  src/components/Divider.jsx
  src/components/FullUserPost.jsx
  src/components/Header.jsx
  src/components/MvdList.css
  src/components/MvdList.jsx
  src/components/MySelectTag.css
  src/components/MySelectTag.jsx
  src/components/Weather.jsx
  src/components/createPostBtn.css
  src/components/routes/Destination.css
  src/components/routes/Destination.jsx
  src/components/routes/Home.jsx
  src/components/routes/PostDetails.css
  src/components/routes/PostDetails.jsx
  src/components/weather.css
  src/css/AbstractBlogPost.css
  src/css/Converter.css
  src/css/FullUserPost.css
  src/css/Header.css
  src/css/Home.css
  src/css/destinationBloc.css
Labels: Ready for prod

#30 Converter
  src/components/Converter.jsx
  src/components/DestinationBloc.jsx
Labels: Ready for prod

#29 Fixedcontactus
  package-lock.json
  src/components/MySelectTag.css
Labels: Ready for prod

#32 desktop version improvements
  src/components/Footer.css
  src/components/Map.jsx
  src/components/MvdList.jsx
  src/components/Team.jsx
  src/components/routes/ContactUs.css
  src/components/routes/ContactUs.jsx
  src/css/Home.css
  src/css/Team.css
Labels: Ready for validation

#31 Fix redirection problems in Links in search bar and linked to new cou…
  src/components/routes/Home.jsx
  src/css/Home.css
Labels: Fixed - ready for prod

#33 Upload img
  package-lock.json
  src/App.jsx
  src/components/CreatePostBtn.jsx
  src/components/MySelectTag.css
  src/components/MySelectTag.jsx
  src/components/NewPostForm.jsx
  src/css/NewPostForm.css
Labels: Ready for prod

#34 CSS improved and pictures uploading system added
  .env.sample
  package-lock.json
  package.json
  src/components/NewPostForm.jsx
  src/components/TagList.jsx
  src/components/Team.jsx
  src/css/Home.css
  src/css/NewPostForm.css
  src/css/Team.css
Labels: Ready for prod

#35 Weather
  package-lock.json
  src/components/Weather.jsx
  src/components/weather.css
  src/css/Converter.css
  src/css/destinationBloc.css
  yarn.lock
Labels: Ready for prod

#36 Express api - fixed link pbm
  package-lock.json
  package.json
  src/assets/Japan1.png
  src/assets/Japan2.jpg
  src/assets/Japan4.png
  src/assets/euro.png
  src/assets/japan3.jpeg
  src/assets/swiss.png
  src/components/AbstractBlogPost.jsx
  src/components/Converter.jsx
  src/components/FullUserPost.jsx
  src/components/NewPostForm.jsx
  src/components/Weather.jsx
  src/components/routes/PostDetails.jsx
  src/css/AbstractBlogPost.css
Labels: Ready for prod, Fixed - ready for prod

#38 Carousel
  public/index.html
  src/assets/90244468.jpg
  src/assets/Flag_of_Japan.png
  src/assets/LTInternet-Regular.ttf
  src/assets/Logo.svg
  src/assets/Zag Regular.otf
  src/assets/avatar.jpg
  src/assets/coolvetica-condensed-rg.ttf
  src/assets/favicon.png
  src/assets/gelasio-regular.ttf
  src/assets/logoV2.png
  src/assets/logoV2.svg
  src/assets/logoV3.png
  src/assets/logoV3.svg
  src/assets/logoV4.png
  src/assets/logoV4.svg
  src/assets/newLogo.png
  src/assets/newLogoPink.svg
  src/assets/nico.jpg
  src/assets/wll.jpg
  src/components/CreatePostBtn.jsx
  src/components/DestinationBloc.jsx
  src/components/Footer.jsx
  src/components/MvdList.jsx
  src/components/MySelectTag.jsx
  src/components/NewPostForm.jsx
  src/components/Team.jsx
  src/components/Weather.jsx
  src/components/routes/ContactUs.jsx
  src/components/routes/Destination.jsx
  src/components/routes/Filter.jsx
  src/components/routes/Home.jsx
  src/components/routes/PostDetails.jsx
  src/css/ContactUs.css
  src/css/Destination.css
  src/css/Filter.css
  src/css/Footer.css
  src/css/Header.css
  src/css/Home.css
  src/css/MvdList.css
  src/css/MySelectTag.css
  src/css/NewPostForm.css
  src/css/PostDetails.css
  src/css/Team.css
  src/css/createPostBtn.css
  src/css/destinationBloc.css
  src/css/index.css
  src/css/weather.css
Labels: Ready for prod, Conflicts

#39 Quizz
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  src/App.jsx
  src/assets/choice.png
  src/assets/fav-icon.png
  src/assets/favicon.png
  src/assets/hangingLetters.png
  src/components/Converter.jsx
  src/components/Header.jsx
  src/components/MvdList.jsx
  src/components/Questionaire.jsx
  src/components/routes/Quizz.jsx
  src/css/Converter.css
  src/css/Header.css
  src/css/Home.css
  src/css/Quizz.css
Labels: Fixed - ready for prod

#40 link api to db
  src/components/AbstractBlogPost.jsx
  src/components/routes/PostDetails.jsx
Labels: Ready for prod

#42 mvd list randomized and css improved
  src/components/DestinationBloc.jsx
  src/components/MvdList.jsx
  src/components/Weather.jsx
  src/components/routes/Destination.jsx
  src/css/Destination.css
  src/css/Quizz.css
  src/css/weather.css
Labels: Ready for prod

#41 Comment user
  package-lock.json
  src/components/CommentForm.jsx
  src/components/NewPostForm.jsx
  src/components/routes/PostDetails.jsx
  yarn.lock
Labels: Ready for prod

#43 Db setup
  package-lock.json
  package.json
  src/components/AbstractBlogPost.jsx
  src/components/Comment.jsx
  src/components/CommentForm.jsx
  src/components/routes/PostDetails.jsx
  src/css/PostDetails.css
Labels: Ready for prod

#44 avatar added to post form
  src/components/Converter.jsx
  src/components/MvdList.jsx
  src/components/NewPostForm.jsx
  src/css/Footer.css
  src/css/NewPostForm.css
Labels: Ready for prod

#45 Weather
  src/components/Weather.jsx
Labels: Ready for prod

#47 404 error page created
  src/components/Error.jsx
  src/components/MvdList.jsx
  src/components/routes/Home.jsx
Labels: Ready for prod

#46 Dashbord in work
  src/App.jsx
  src/components/Header.jsx
  src/components/routes/Dashboard.jsx
  src/css/Dashboard.css
Labels: Ready for prod

#48 Avatar
  src/App.jsx
  src/components/Error.jsx
  src/css/Error.css
Labels: Ready for prod

#49 Cssfix
  src/components/NewPostForm.jsx
  src/css/NewPostForm.css
Labels: Ready for prod

#50 Weather
  src/components/Weather.jsx
Labels: Ready for prod

#55 Fixbug nc
  package-lock.json
  src/components/CommentForm.jsx
  src/components/routes/Dashboard.jsx
  src/css/CommentForm.css
  src/css/MySelectTag.css
  src/css/NewPostForm.css
  yarn.lock
Labels: Ready for prod

#54 add filter to posts
  package-lock.json
  package.json
  src/App.jsx
  src/components/AbstractBlogPost.jsx
  src/components/MySelectTag.jsx
  src/components/NewPostForm.jsx
  src/components/SearchBtn.jsx
  src/components/routes/Destination.jsx
  src/contexts/DisplayPostsContext.jsx
Labels: Ready for prod

#52 Debug
  .eslintrc.json
  public/manifest.json
  src/components/Converter.jsx
  src/components/Map.jsx
  src/components/MvdList.jsx
  src/components/Team.jsx
  src/components/routes/Home.jsx
  src/css/AbstractBlogPost.css
  src/css/ContactUs.css
  src/css/Converter.css
  src/css/Dashboard.css
  src/css/Destination.css
  src/css/Home.css
  src/css/TagList.css
  src/css/Team.css
Labels: Ready for prod

#51 database localhost port changed
  src/css/Destination.css
Labels: Ready for prod

#53 Cleaning code
  src/components/CommentForm.jsx
  src/components/CreatePostBtn.jsx
  src/components/NewPostForm.jsx
  src/components/Weather.jsx
  src/components/routes/ContactUs.jsx
  src/components/routes/PostDetails.jsx
Labels: Ready for prod

#59 tag-btn css improved
  src/App.jsx
  src/components/MySelectTag.jsx
  src/components/SearchBtn.jsx
  src/css/MySelectTag.css
Labels: Ready for prod

#58 all say in branch name
  src/css/CommentForm.css
Labels: Ready for prod

#57 minor changes on weather and converter
  src/components/Converter.jsx
  src/components/Weather.jsx
Labels: Ready for prod

#60 fix bug
  src/components/AbstractBlogPost.jsx
  src/components/routes/PostDetails.jsx
Labels: Ready for prod

#62 tag-btn css issues fixed
  src/components/AbstractBlogPost.jsx
  src/components/Converter.jsx
  src/components/routes/Dashboard.jsx
  src/css/AbstractBlogPost.css
  src/css/Converter.css
  src/css/Dashboard.css
  src/css/Destination.css
  src/css/MySelectTag.css
Labels: Ready for validation

#64 Add refresh on comment submission
  src/components/CommentForm.jsx
Labels: Ready for prod

#66 required on date in newpostform
  src/components/NewPostForm.jsx
Labels: Ready for prod

#67 logo issues improved
  src/css/Header.css
Labels: Ready for prod

#69 add default avatar to post comment
  src/components/AbstractBlogPost.jsx
  src/components/CommentForm.jsx
  src/components/DestinationBloc.jsx
  src/components/NewPostForm.jsx
  src/components/routes/PostDetails.jsx
Labels: Ready for prod
